feat: payment details
jcloudify/jcloudify-ui pull request #41
Opened 2024-08-22 10:55 UTC by Noums26

2024-08-22 11:33 UTC, YumeT023 requested changes

2024-08-22 11:33 UTC, YumeT023 commented on src/operations/payment-methods/PaymentMethodForm.tsx
> +  const [isSubmiting, setIsSubmiting] = useState(false);
already exposed in the 2nd element of the useCreate array
```typescript
[create, { is... }] = useCreate()
```

2024-08-22 11:33 UTC, YumeT023 commented on src/operations/payment-methods/PaymentMethodForm.tsx
> +  const submitPaymentInfo = async (e: any) => {
any ?

2024-08-22 11:33 UTC, YumeT023 commented on src/operations/payment-methods/PaymentMethodForm.tsx
> +export const PaymentMethodForm: React.FC<{onSuccess: () => void}> = ({
use React admin `Create/CreateBase` directly

2024-08-22 11:33 UTC, YumeT023 commented on src/operations/payment-details/PaymentDetails.tsx
> +        <IconButtonWithTooltip
doesnt IconButtonWithTooltip expose a 'to' prop for navigation ? leave it as is if it doesnt

2024-08-22 11:33 UTC, YumeT023 commented on src/operations/payment-methods/BankCardShow.tsx
> +  const stripePk = process.env.REACT_APP_STRIPE_PK;
check config/env.ts 

do not use process.env.thing in-code, put them in config/env.ts first

2024-08-22 11:33 UTC, YumeT023 commented on src/operations/payment-methods/BankCardShow.tsx
> +export const BankCardShow: React.FC<{last4: string}> = ({last4}) => {
last4 -> last4Digit

2024-08-22 11:33 UTC, YumeT023 commented on src/operations/payment-methods/PaymentMethods.tsx
> +import {PaymentMethodForm} from "./PaymentMethodForm";
always use "@/stuff" location for imports

2024-08-22 11:33 UTC, YumeT023 commented on src/operations/payment-details/PaymentDetails.tsx
> +import {IconButtonWithTooltip} from "react-admin";
why is there payment-details, payment-methods, payments folder ?

delete all the folders about payments, only leave payments there, then put everything about payments in there
you are always allowed to create multiple providers, but not multiple operations module about a feature

2024-08-28 13:47 UTC, Noums26 commented on src/operations/payment-methods/PaymentMethodForm.tsx
> +  const [isSubmiting, setIsSubmiting] = useState(false);
Yes but is... remains unchanged during and after the operation.

2024-08-28 13:51 UTC, Noums26 commented on src/operations/payment-methods/PaymentMethodForm.tsx
> +export const PaymentMethodForm: React.FC<{onSuccess: () => void}> = ({
The stripe element must be submitted first to obtain the ID.

2024-11-06 08:37 UTC, closed without merging