feat: app billing info
jcloudify/jcloudify-ui pull request #74
Opened 2024-10-08 13:42 UTC by Noums26

2024-10-11 12:34 UTC, YumeT023 requested changes
filename -> main component name
distinguish the payment from the billing itself!

2024-10-11 12:34 UTC, YumeT023 commented on src/operations/billing/BillingInformation.tsx
> +
rename the file into the component's name

2024-10-11 12:34 UTC, YumeT023 commented on src/providers/paymentDetailsProvider.ts
> +import {paymentApi, unwrap} from "../services/poja-api";
fix imports path

2024-10-11 12:34 UTC, YumeT023 commented on src/operations/apps/AppBilling.tsx
> +              {env.environment_type} - $ {resource.computed_price}
use EnvironmentType component to display component environment_type

2024-10-11 12:34 UTC, YumeT023 commented on src/operations/apps/appShowViews.tsx
> +    ":billingId": <></>,
useless

2024-10-11 12:34 UTC, YumeT023 commented on src/operations/billing/Billing.tsx
> +  const customerId = authProvider.getCachedWhoami()?.user?.stripe_id!;
this can be retrieved from the provider !

2024-10-11 12:34 UTC, YumeT023 commented on src/operations/billing/Payments.tsx
> +import {BillingSummary} from "./Billing";
fix import path

2024-10-11 12:34 UTC, YumeT023 commented on src/operations/billing/Payments.tsx
> +  return (
inline return

2024-10-11 12:34 UTC, YumeT023 commented on src/operations/billing/ShowBillingInfo.tsx
> +      <SimpleShowLayout>
no!

use the custom ShowLayout from operations/components/show

remove emptyWhileLoading

2024-10-11 12:34 UTC, YumeT023 commented on src/providers/billingInfoProvider.ts
> +  getList: function (): Promise<PagedResponse<ToRecord<BillingInfo>>> {
rm return types

2024-10-11 12:34 UTC, YumeT023 commented on src/providers/billingInfoProvider.ts
> +  data: BillingInfo[],
data -> billingInfos

2024-10-11 12:34 UTC, YumeT023 commented on src/providers/billingInfoProvider.ts
> +        const res = await unwrap(() =>
res -> userAppBillingInfo

2024-10-11 12:34 UTC, YumeT023 commented on src/operations/billing/ShowBillingInfo.tsx
> +              <Typography variant={"h4"}>
no need explicit typing in the render fn, 

instead


<FunctionField<ToRecord<BillingInfo>> 
  render={...}
/>

2024-10-15 10:52 UTC, YumeT023 requested changes

2024-10-15 10:52 UTC, YumeT023 commented on src/operations/apps/AppBilling.tsx
>    const {data: environments = []} = useListContext<ToRecord<Environment>>();
use, WithListContext component to get the data prop to map

2024-10-15 10:52 UTC, YumeT023 commented on src/operations/billing/Billing.tsx
> +import {ShowBillingInfo} from "./";
fix import path

2024-10-15 10:52 UTC, YumeT023 commented on src/operations/billing/Billing.tsx
> +export const BillingSummary: React.FC = () => (
do not export

2024-10-15 10:52 UTC, YumeT023 commented on src/operations/billing/Billing.tsx
> +        <PaymentDeatilsShow />
PaymentDetailsShow typo

2024-10-15 10:52 UTC, YumeT023 commented on src/operations/billing/Billing.tsx
> +export const BillingSummary: React.FC = () => (
why do you separate the BillingSummary and the Billing component ?... ?

2024-10-15 10:52 UTC, YumeT023 commented on src/operations/billing/ShowBillingInfo.tsx
> +                <Typography variant={"h4"}>
no need curly brackets

2024-10-15 10:52 UTC, YumeT023 commented on src/operations/billing/index.ts
> +  list: Billing,
put // TODO: custom Menu

2024-10-15 10:52 UTC, YumeT023 commented on src/operations/billing/index.ts
> +export * from "../payments/Payments";
??!!

2024-10-15 10:52 UTC, YumeT023 commented on src/operations/payments/Payments.tsx
> +    <BillingSummary />
separate the Billing itself and the BillingSummary

2024-10-15 10:52 UTC, YumeT023 commented on src/providers/billingInfoProvider.ts
> +import {PojaDataProvider, ToRecord} from "./types";
fix imports path

2024-10-15 10:52 UTC, YumeT023 commented on src/providers/billingInfoProvider.ts
>  import {authProvider} from "./authProvider";
import paths

2024-10-15 10:52 UTC, YumeT023 commented on src/operations/apps/AppBilling.tsx
> +const BillingShow = () => {
put this in ./billing/BillingShow.tsx

2024-10-15 10:52 UTC, YumeT023 commented on src/operations/apps/AppBilling.tsx
> +const BillingInfoDetails: React.FC<{env: Environment; appId: string}> = ({
amboary pr

2024-10-16 11:21 UTC, Noums26 commented on src/operations/billing/Billing.tsx
> +        <ShowBillingInfo />
BillingInfoShow

2024-10-16 11:22 UTC, Noums26 commented on src/operations/billing/BillingShow.tsx
> +const BillingInfoDetails: React.FC<{env: Environment; appId: string}> = ({
BillingInfoDetailsShow

2024-10-17 10:03 UTC, YumeT023 requested changes

2024-10-17 10:03 UTC, YumeT023 commented on src/operations/billing/BillingInfoShow.tsx
> +}> = ({targetId = "summary", targetResource = "summary"}) => (
"*"

2024-10-17 10:03 UTC, YumeT023 commented on src/operations/billing/BillingShow.tsx
> +import {ContainerWithHeading} from "@/components/container";
@/components goes before @/operations/...

@/operations/.... goes before @/providers

2024-10-17 10:49 UTC, YumeT023 requested changes

2024-10-17 10:49 UTC, YumeT023 commented on src/operations/billing/BillingShow.tsx
> +  return (
inline return

2024-10-17 11:08 UTC, merged